// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/core/core.proto

package core

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Difficulty int32

const (
	Difficulty_DIFFICULTY_UNSPECIFIED Difficulty = 0
	Difficulty_DIFFICULTY_EASY        Difficulty = 1
	Difficulty_DIFFICULTY_MEDIUM      Difficulty = 2
	Difficulty_DIFFICULTY_HARD        Difficulty = 3
)

// Enum value maps for Difficulty.
var (
	Difficulty_name = map[int32]string{
		0: "DIFFICULTY_UNSPECIFIED",
		1: "DIFFICULTY_EASY",
		2: "DIFFICULTY_MEDIUM",
		3: "DIFFICULTY_HARD",
	}
	Difficulty_value = map[string]int32{
		"DIFFICULTY_UNSPECIFIED": 0,
		"DIFFICULTY_EASY":        1,
		"DIFFICULTY_MEDIUM":      2,
		"DIFFICULTY_HARD":        3,
	}
)

func (x Difficulty) Enum() *Difficulty {
	p := new(Difficulty)
	*p = x
	return p
}

func (x Difficulty) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Difficulty) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_core_core_proto_enumTypes[0].Descriptor()
}

func (Difficulty) Type() protoreflect.EnumType {
	return &file_proto_core_core_proto_enumTypes[0]
}

func (x Difficulty) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Difficulty.Descriptor instead.
func (Difficulty) EnumDescriptor() ([]byte, []int) {
	return file_proto_core_core_proto_rawDescGZIP(), []int{0}
}

type QuestionType int32

const (
	QuestionType_QUESTION_TYPE_UNSPECIFIED   QuestionType = 0
	QuestionType_QUESTION_TYPE_THEORY        QuestionType = 1
	QuestionType_QUESTION_TYPE_CODING        QuestionType = 2
	QuestionType_QUESTION_TYPE_SYSTEM_DESIGN QuestionType = 3
	QuestionType_QUESTION_TYPE_ALGORITHM     QuestionType = 4
)

// Enum value maps for QuestionType.
var (
	QuestionType_name = map[int32]string{
		0: "QUESTION_TYPE_UNSPECIFIED",
		1: "QUESTION_TYPE_THEORY",
		2: "QUESTION_TYPE_CODING",
		3: "QUESTION_TYPE_SYSTEM_DESIGN",
		4: "QUESTION_TYPE_ALGORITHM",
	}
	QuestionType_value = map[string]int32{
		"QUESTION_TYPE_UNSPECIFIED":   0,
		"QUESTION_TYPE_THEORY":        1,
		"QUESTION_TYPE_CODING":        2,
		"QUESTION_TYPE_SYSTEM_DESIGN": 3,
		"QUESTION_TYPE_ALGORITHM":     4,
	}
)

func (x QuestionType) Enum() *QuestionType {
	p := new(QuestionType)
	*p = x
	return p
}

func (x QuestionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QuestionType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_core_core_proto_enumTypes[1].Descriptor()
}

func (QuestionType) Type() protoreflect.EnumType {
	return &file_proto_core_core_proto_enumTypes[1]
}

func (x QuestionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QuestionType.Descriptor instead.
func (QuestionType) EnumDescriptor() ([]byte, []int) {
	return file_proto_core_core_proto_rawDescGZIP(), []int{1}
}

type AnswerQuality int32

const (
	AnswerQuality_ANSWER_QUALITY_AGAIN AnswerQuality = 0
	AnswerQuality_ANSWER_QUALITY_HARD  AnswerQuality = 3
	AnswerQuality_ANSWER_QUALITY_GOOD  AnswerQuality = 4
	AnswerQuality_ANSWER_QUALITY_EASY  AnswerQuality = 5
)

// Enum value maps for AnswerQuality.
var (
	AnswerQuality_name = map[int32]string{
		0: "ANSWER_QUALITY_AGAIN",
		3: "ANSWER_QUALITY_HARD",
		4: "ANSWER_QUALITY_GOOD",
		5: "ANSWER_QUALITY_EASY",
	}
	AnswerQuality_value = map[string]int32{
		"ANSWER_QUALITY_AGAIN": 0,
		"ANSWER_QUALITY_HARD":  3,
		"ANSWER_QUALITY_GOOD":  4,
		"ANSWER_QUALITY_EASY":  5,
	}
)

func (x AnswerQuality) Enum() *AnswerQuality {
	p := new(AnswerQuality)
	*p = x
	return p
}

func (x AnswerQuality) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AnswerQuality) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_core_core_proto_enumTypes[2].Descriptor()
}

func (AnswerQuality) Type() protoreflect.EnumType {
	return &file_proto_core_core_proto_enumTypes[2]
}

func (x AnswerQuality) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AnswerQuality.Descriptor instead.
func (AnswerQuality) EnumDescriptor() ([]byte, []int) {
	return file_proto_core_core_proto_rawDescGZIP(), []int{2}
}

type Tag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tag) Reset() {
	*x = Tag{}
	mi := &file_proto_core_core_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_core_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_proto_core_core_proto_rawDescGZIP(), []int{0}
}

func (x *Tag) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Tag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Question struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	ContentMd     *string                `protobuf:"bytes,3,opt,name=content_md,json=contentMd,proto3,oneof" json:"content_md,omitempty"`
	AnswerMd      *string                `protobuf:"bytes,4,opt,name=answer_md,json=answerMd,proto3,oneof" json:"answer_md,omitempty"`
	Difficulty    Difficulty             `protobuf:"varint,5,opt,name=difficulty,proto3,enum=core.Difficulty" json:"difficulty,omitempty"`
	Type          QuestionType           `protobuf:"varint,6,opt,name=type,proto3,enum=core.QuestionType" json:"type,omitempty"`
	TagIds        []int32                `protobuf:"varint,7,rep,packed,name=tag_ids,json=tagIds,proto3" json:"tag_ids,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Question) Reset() {
	*x = Question{}
	mi := &file_proto_core_core_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Question) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Question) ProtoMessage() {}

func (x *Question) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_core_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Question.ProtoReflect.Descriptor instead.
func (*Question) Descriptor() ([]byte, []int) {
	return file_proto_core_core_proto_rawDescGZIP(), []int{1}
}

func (x *Question) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Question) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Question) GetContentMd() string {
	if x != nil && x.ContentMd != nil {
		return *x.ContentMd
	}
	return ""
}

func (x *Question) GetAnswerMd() string {
	if x != nil && x.AnswerMd != nil {
		return *x.AnswerMd
	}
	return ""
}

func (x *Question) GetDifficulty() Difficulty {
	if x != nil {
		return x.Difficulty
	}
	return Difficulty_DIFFICULTY_UNSPECIFIED
}

func (x *Question) GetType() QuestionType {
	if x != nil {
		return x.Type
	}
	return QuestionType_QUESTION_TYPE_UNSPECIFIED
}

func (x *Question) GetTagIds() []int32 {
	if x != nil {
		return x.TagIds
	}
	return nil
}

func (x *Question) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Question) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type UserProgress struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	QuestionId     string                 `protobuf:"bytes,3,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	Repetitions    int32                  `protobuf:"varint,4,opt,name=repetitions,proto3" json:"repetitions,omitempty"`
	EaseFactor     float32                `protobuf:"fixed32,5,opt,name=ease_factor,json=easeFactor,proto3" json:"ease_factor,omitempty"`
	IntervalDays   int32                  `protobuf:"varint,6,opt,name=interval_days,json=intervalDays,proto3" json:"interval_days,omitempty"`
	LastReviewedAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=last_reviewed_at,json=lastReviewedAt,proto3" json:"last_reviewed_at,omitempty"`
	NextReviewAt   *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=next_review_at,json=nextReviewAt,proto3" json:"next_review_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UserProgress) Reset() {
	*x = UserProgress{}
	mi := &file_proto_core_core_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProgress) ProtoMessage() {}

func (x *UserProgress) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_core_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProgress.ProtoReflect.Descriptor instead.
func (*UserProgress) Descriptor() ([]byte, []int) {
	return file_proto_core_core_proto_rawDescGZIP(), []int{2}
}

func (x *UserProgress) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserProgress) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserProgress) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

func (x *UserProgress) GetRepetitions() int32 {
	if x != nil {
		return x.Repetitions
	}
	return 0
}

func (x *UserProgress) GetEaseFactor() float32 {
	if x != nil {
		return x.EaseFactor
	}
	return 0
}

func (x *UserProgress) GetIntervalDays() int32 {
	if x != nil {
		return x.IntervalDays
	}
	return 0
}

func (x *UserProgress) GetLastReviewedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastReviewedAt
	}
	return nil
}

func (x *UserProgress) GetNextReviewAt() *timestamppb.Timestamp {
	if x != nil {
		return x.NextReviewAt
	}
	return nil
}

type GetQuestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionId    string                 `protobuf:"bytes,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuestionRequest) Reset() {
	*x = GetQuestionRequest{}
	mi := &file_proto_core_core_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuestionRequest) ProtoMessage() {}

func (x *GetQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_core_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuestionRequest.ProtoReflect.Descriptor instead.
func (*GetQuestionRequest) Descriptor() ([]byte, []int) {
	return file_proto_core_core_proto_rawDescGZIP(), []int{3}
}

func (x *GetQuestionRequest) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

type ListQuestionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Type          *QuestionType          `protobuf:"varint,3,opt,name=type,proto3,enum=core.QuestionType,oneof" json:"type,omitempty"`
	Difficulty    *Difficulty            `protobuf:"varint,4,opt,name=difficulty,proto3,enum=core.Difficulty,oneof" json:"difficulty,omitempty"`
	TagIds        []int32                `protobuf:"varint,5,rep,packed,name=tag_ids,json=tagIds,proto3" json:"tag_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListQuestionsRequest) Reset() {
	*x = ListQuestionsRequest{}
	mi := &file_proto_core_core_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListQuestionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQuestionsRequest) ProtoMessage() {}

func (x *ListQuestionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_core_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQuestionsRequest.ProtoReflect.Descriptor instead.
func (*ListQuestionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_core_core_proto_rawDescGZIP(), []int{4}
}

func (x *ListQuestionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListQuestionsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListQuestionsRequest) GetType() QuestionType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return QuestionType_QUESTION_TYPE_UNSPECIFIED
}

func (x *ListQuestionsRequest) GetDifficulty() Difficulty {
	if x != nil && x.Difficulty != nil {
		return *x.Difficulty
	}
	return Difficulty_DIFFICULTY_UNSPECIFIED
}

func (x *ListQuestionsRequest) GetTagIds() []int32 {
	if x != nil {
		return x.TagIds
	}
	return nil
}

type ListQuestionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Questions     []*Question            `protobuf:"bytes,1,rep,name=questions,proto3" json:"questions,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListQuestionsResponse) Reset() {
	*x = ListQuestionsResponse{}
	mi := &file_proto_core_core_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListQuestionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQuestionsResponse) ProtoMessage() {}

func (x *ListQuestionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_core_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQuestionsResponse.ProtoReflect.Descriptor instead.
func (*ListQuestionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_core_core_proto_rawDescGZIP(), []int{5}
}

func (x *ListQuestionsResponse) GetQuestions() []*Question {
	if x != nil {
		return x.Questions
	}
	return nil
}

func (x *ListQuestionsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type CreateQuestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	ContentMd     *string                `protobuf:"bytes,2,opt,name=content_md,json=contentMd,proto3,oneof" json:"content_md,omitempty"`
	AnswerMd      *string                `protobuf:"bytes,3,opt,name=answer_md,json=answerMd,proto3,oneof" json:"answer_md,omitempty"`
	Difficulty    Difficulty             `protobuf:"varint,4,opt,name=difficulty,proto3,enum=core.Difficulty" json:"difficulty,omitempty"`
	Type          QuestionType           `protobuf:"varint,5,opt,name=type,proto3,enum=core.QuestionType" json:"type,omitempty"`
	TagIds        []int32                `protobuf:"varint,6,rep,packed,name=tag_ids,json=tagIds,proto3" json:"tag_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateQuestionRequest) Reset() {
	*x = CreateQuestionRequest{}
	mi := &file_proto_core_core_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateQuestionRequest) ProtoMessage() {}

func (x *CreateQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_core_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateQuestionRequest.ProtoReflect.Descriptor instead.
func (*CreateQuestionRequest) Descriptor() ([]byte, []int) {
	return file_proto_core_core_proto_rawDescGZIP(), []int{6}
}

func (x *CreateQuestionRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateQuestionRequest) GetContentMd() string {
	if x != nil && x.ContentMd != nil {
		return *x.ContentMd
	}
	return ""
}

func (x *CreateQuestionRequest) GetAnswerMd() string {
	if x != nil && x.AnswerMd != nil {
		return *x.AnswerMd
	}
	return ""
}

func (x *CreateQuestionRequest) GetDifficulty() Difficulty {
	if x != nil {
		return x.Difficulty
	}
	return Difficulty_DIFFICULTY_UNSPECIFIED
}

func (x *CreateQuestionRequest) GetType() QuestionType {
	if x != nil {
		return x.Type
	}
	return QuestionType_QUESTION_TYPE_UNSPECIFIED
}

func (x *CreateQuestionRequest) GetTagIds() []int32 {
	if x != nil {
		return x.TagIds
	}
	return nil
}

type DeleteQuestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionId    string                 `protobuf:"bytes,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteQuestionRequest) Reset() {
	*x = DeleteQuestionRequest{}
	mi := &file_proto_core_core_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteQuestionRequest) ProtoMessage() {}

func (x *DeleteQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_core_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteQuestionRequest.ProtoReflect.Descriptor instead.
func (*DeleteQuestionRequest) Descriptor() ([]byte, []int) {
	return file_proto_core_core_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteQuestionRequest) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

type UpdateQuestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionId    string                 `protobuf:"bytes,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	Title         *string                `protobuf:"bytes,2,opt,name=title,proto3,oneof" json:"title,omitempty"`
	ContentMd     *string                `protobuf:"bytes,3,opt,name=content_md,json=contentMd,proto3,oneof" json:"content_md,omitempty"`
	AnswerMd      *string                `protobuf:"bytes,4,opt,name=answer_md,json=answerMd,proto3,oneof" json:"answer_md,omitempty"`
	Type          *QuestionType          `protobuf:"varint,5,opt,name=type,proto3,enum=core.QuestionType,oneof" json:"type,omitempty"`
	Difficulty    *Difficulty            `protobuf:"varint,6,opt,name=difficulty,proto3,enum=core.Difficulty,oneof" json:"difficulty,omitempty"`
	TagIds        []int32                `protobuf:"varint,7,rep,packed,name=tag_ids,json=tagIds,proto3" json:"tag_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateQuestionRequest) Reset() {
	*x = UpdateQuestionRequest{}
	mi := &file_proto_core_core_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateQuestionRequest) ProtoMessage() {}

func (x *UpdateQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_core_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateQuestionRequest.ProtoReflect.Descriptor instead.
func (*UpdateQuestionRequest) Descriptor() ([]byte, []int) {
	return file_proto_core_core_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateQuestionRequest) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

func (x *UpdateQuestionRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *UpdateQuestionRequest) GetContentMd() string {
	if x != nil && x.ContentMd != nil {
		return *x.ContentMd
	}
	return ""
}

func (x *UpdateQuestionRequest) GetAnswerMd() string {
	if x != nil && x.AnswerMd != nil {
		return *x.AnswerMd
	}
	return ""
}

func (x *UpdateQuestionRequest) GetType() QuestionType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return QuestionType_QUESTION_TYPE_UNSPECIFIED
}

func (x *UpdateQuestionRequest) GetDifficulty() Difficulty {
	if x != nil && x.Difficulty != nil {
		return *x.Difficulty
	}
	return Difficulty_DIFFICULTY_UNSPECIFIED
}

func (x *UpdateQuestionRequest) GetTagIds() []int32 {
	if x != nil {
		return x.TagIds
	}
	return nil
}

type CreateTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTagRequest) Reset() {
	*x = CreateTagRequest{}
	mi := &file_proto_core_core_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTagRequest) ProtoMessage() {}

func (x *CreateTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_core_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTagRequest.ProtoReflect.Descriptor instead.
func (*CreateTagRequest) Descriptor() ([]byte, []int) {
	return file_proto_core_core_proto_rawDescGZIP(), []int{9}
}

func (x *CreateTagRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTagRequest) Reset() {
	*x = DeleteTagRequest{}
	mi := &file_proto_core_core_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTagRequest) ProtoMessage() {}

func (x *DeleteTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_core_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTagRequest.ProtoReflect.Descriptor instead.
func (*DeleteTagRequest) Descriptor() ([]byte, []int) {
	return file_proto_core_core_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteTagRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListTagsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          []*Tag                 `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTagsResponse) Reset() {
	*x = ListTagsResponse{}
	mi := &file_proto_core_core_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTagsResponse) ProtoMessage() {}

func (x *ListTagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_core_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTagsResponse.ProtoReflect.Descriptor instead.
func (*ListTagsResponse) Descriptor() ([]byte, []int) {
	return file_proto_core_core_proto_rawDescGZIP(), []int{11}
}

func (x *ListTagsResponse) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

type GetNextQuestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type          *QuestionType          `protobuf:"varint,2,opt,name=type,proto3,enum=core.QuestionType,oneof" json:"type,omitempty"`
	TagIds        []int32                `protobuf:"varint,3,rep,packed,name=tag_ids,json=tagIds,proto3" json:"tag_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNextQuestionRequest) Reset() {
	*x = GetNextQuestionRequest{}
	mi := &file_proto_core_core_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNextQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNextQuestionRequest) ProtoMessage() {}

func (x *GetNextQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_core_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNextQuestionRequest.ProtoReflect.Descriptor instead.
func (*GetNextQuestionRequest) Descriptor() ([]byte, []int) {
	return file_proto_core_core_proto_rawDescGZIP(), []int{12}
}

func (x *GetNextQuestionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetNextQuestionRequest) GetType() QuestionType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return QuestionType_QUESTION_TYPE_UNSPECIFIED
}

func (x *GetNextQuestionRequest) GetTagIds() []int32 {
	if x != nil {
		return x.TagIds
	}
	return nil
}

type GetUserProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionId    string                 `protobuf:"bytes,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserProgressRequest) Reset() {
	*x = GetUserProgressRequest{}
	mi := &file_proto_core_core_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProgressRequest) ProtoMessage() {}

func (x *GetUserProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_core_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProgressRequest.ProtoReflect.Descriptor instead.
func (*GetUserProgressRequest) Descriptor() ([]byte, []int) {
	return file_proto_core_core_proto_rawDescGZIP(), []int{13}
}

func (x *GetUserProgressRequest) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

func (x *GetUserProgressRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type RecordAnswerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionId    string                 `protobuf:"bytes,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AnswerQuality AnswerQuality          `protobuf:"varint,3,opt,name=answer_quality,json=answerQuality,proto3,enum=core.AnswerQuality" json:"answer_quality,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordAnswerRequest) Reset() {
	*x = RecordAnswerRequest{}
	mi := &file_proto_core_core_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordAnswerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordAnswerRequest) ProtoMessage() {}

func (x *RecordAnswerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_core_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordAnswerRequest.ProtoReflect.Descriptor instead.
func (*RecordAnswerRequest) Descriptor() ([]byte, []int) {
	return file_proto_core_core_proto_rawDescGZIP(), []int{14}
}

func (x *RecordAnswerRequest) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

func (x *RecordAnswerRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RecordAnswerRequest) GetAnswerQuality() AnswerQuality {
	if x != nil {
		return x.AnswerQuality
	}
	return AnswerQuality_ANSWER_QUALITY_AGAIN
}

var File_proto_core_core_proto protoreflect.FileDescriptor

const file_proto_core_core_proto_rawDesc = "" +
	"\n" +
	"\x15proto/core/core.proto\x12\x04core\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\")\n" +
	"\x03Tag\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xfc\x02\n" +
	"\bQuestion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\"\n" +
	"\n" +
	"content_md\x18\x03 \x01(\tH\x00R\tcontentMd\x88\x01\x01\x12 \n" +
	"\tanswer_md\x18\x04 \x01(\tH\x01R\banswerMd\x88\x01\x01\x120\n" +
	"\n" +
	"difficulty\x18\x05 \x01(\x0e2\x10.core.DifficultyR\n" +
	"difficulty\x12&\n" +
	"\x04type\x18\x06 \x01(\x0e2\x12.core.QuestionTypeR\x04type\x12\x17\n" +
	"\atag_ids\x18\a \x03(\x05R\x06tagIds\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\r\n" +
	"\v_content_mdB\f\n" +
	"\n" +
	"_answer_md\"\xc8\x02\n" +
	"\fUserProgress\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1f\n" +
	"\vquestion_id\x18\x03 \x01(\tR\n" +
	"questionId\x12 \n" +
	"\vrepetitions\x18\x04 \x01(\x05R\vrepetitions\x12\x1f\n" +
	"\vease_factor\x18\x05 \x01(\x02R\n" +
	"easeFactor\x12#\n" +
	"\rinterval_days\x18\x06 \x01(\x05R\fintervalDays\x12D\n" +
	"\x10last_reviewed_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x0elastReviewedAt\x12@\n" +
	"\x0enext_review_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\fnextReviewAt\"5\n" +
	"\x12GetQuestionRequest\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\tR\n" +
	"questionId\"\xd9\x01\n" +
	"\x14ListQuestionsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12+\n" +
	"\x04type\x18\x03 \x01(\x0e2\x12.core.QuestionTypeH\x00R\x04type\x88\x01\x01\x125\n" +
	"\n" +
	"difficulty\x18\x04 \x01(\x0e2\x10.core.DifficultyH\x01R\n" +
	"difficulty\x88\x01\x01\x12\x17\n" +
	"\atag_ids\x18\x05 \x03(\x05R\x06tagIdsB\a\n" +
	"\x05_typeB\r\n" +
	"\v_difficulty\"f\n" +
	"\x15ListQuestionsResponse\x12,\n" +
	"\tquestions\x18\x01 \x03(\v2\x0e.core.QuestionR\tquestions\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"\x83\x02\n" +
	"\x15CreateQuestionRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\"\n" +
	"\n" +
	"content_md\x18\x02 \x01(\tH\x00R\tcontentMd\x88\x01\x01\x12 \n" +
	"\tanswer_md\x18\x03 \x01(\tH\x01R\banswerMd\x88\x01\x01\x120\n" +
	"\n" +
	"difficulty\x18\x04 \x01(\x0e2\x10.core.DifficultyR\n" +
	"difficulty\x12&\n" +
	"\x04type\x18\x05 \x01(\x0e2\x12.core.QuestionTypeR\x04type\x12\x17\n" +
	"\atag_ids\x18\x06 \x03(\x05R\x06tagIdsB\r\n" +
	"\v_content_mdB\f\n" +
	"\n" +
	"_answer_md\"8\n" +
	"\x15DeleteQuestionRequest\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\tR\n" +
	"questionId\"\xd5\x02\n" +
	"\x15UpdateQuestionRequest\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\tR\n" +
	"questionId\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tH\x00R\x05title\x88\x01\x01\x12\"\n" +
	"\n" +
	"content_md\x18\x03 \x01(\tH\x01R\tcontentMd\x88\x01\x01\x12 \n" +
	"\tanswer_md\x18\x04 \x01(\tH\x02R\banswerMd\x88\x01\x01\x12+\n" +
	"\x04type\x18\x05 \x01(\x0e2\x12.core.QuestionTypeH\x03R\x04type\x88\x01\x01\x125\n" +
	"\n" +
	"difficulty\x18\x06 \x01(\x0e2\x10.core.DifficultyH\x04R\n" +
	"difficulty\x88\x01\x01\x12\x17\n" +
	"\atag_ids\x18\a \x03(\x05R\x06tagIdsB\b\n" +
	"\x06_titleB\r\n" +
	"\v_content_mdB\f\n" +
	"\n" +
	"_answer_mdB\a\n" +
	"\x05_typeB\r\n" +
	"\v_difficulty\"&\n" +
	"\x10CreateTagRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\"\n" +
	"\x10DeleteTagRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"1\n" +
	"\x10ListTagsResponse\x12\x1d\n" +
	"\x04tags\x18\x01 \x03(\v2\t.core.TagR\x04tags\"\x80\x01\n" +
	"\x16GetNextQuestionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12+\n" +
	"\x04type\x18\x02 \x01(\x0e2\x12.core.QuestionTypeH\x00R\x04type\x88\x01\x01\x12\x17\n" +
	"\atag_ids\x18\x03 \x03(\x05R\x06tagIdsB\a\n" +
	"\x05_type\"R\n" +
	"\x16GetUserProgressRequest\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\tR\n" +
	"questionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\x8b\x01\n" +
	"\x13RecordAnswerRequest\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\tR\n" +
	"questionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12:\n" +
	"\x0eanswer_quality\x18\x03 \x01(\x0e2\x13.core.AnswerQualityR\ranswerQuality*i\n" +
	"\n" +
	"Difficulty\x12\x1a\n" +
	"\x16DIFFICULTY_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fDIFFICULTY_EASY\x10\x01\x12\x15\n" +
	"\x11DIFFICULTY_MEDIUM\x10\x02\x12\x13\n" +
	"\x0fDIFFICULTY_HARD\x10\x03*\x9f\x01\n" +
	"\fQuestionType\x12\x1d\n" +
	"\x19QUESTION_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14QUESTION_TYPE_THEORY\x10\x01\x12\x18\n" +
	"\x14QUESTION_TYPE_CODING\x10\x02\x12\x1f\n" +
	"\x1bQUESTION_TYPE_SYSTEM_DESIGN\x10\x03\x12\x1b\n" +
	"\x17QUESTION_TYPE_ALGORITHM\x10\x04*t\n" +
	"\rAnswerQuality\x12\x18\n" +
	"\x14ANSWER_QUALITY_AGAIN\x10\x00\x12\x17\n" +
	"\x13ANSWER_QUALITY_HARD\x10\x03\x12\x17\n" +
	"\x13ANSWER_QUALITY_GOOD\x10\x04\x12\x17\n" +
	"\x13ANSWER_QUALITY_EASY\x10\x052\xc3\x05\n" +
	"\vCoreService\x127\n" +
	"\vGetQuestion\x12\x18.core.GetQuestionRequest\x1a\x0e.core.Question\x12H\n" +
	"\rListQuestions\x12\x1a.core.ListQuestionsRequest\x1a\x1b.core.ListQuestionsResponse\x12=\n" +
	"\x0eCreateQuestion\x12\x1b.core.CreateQuestionRequest\x1a\x0e.core.Question\x12E\n" +
	"\x0eDeleteQuestion\x12\x1b.core.DeleteQuestionRequest\x1a\x16.google.protobuf.Empty\x12=\n" +
	"\x0eUpdateQuestion\x12\x1b.core.UpdateQuestionRequest\x1a\x0e.core.Question\x12.\n" +
	"\tCreateTag\x12\x16.core.CreateTagRequest\x1a\t.core.Tag\x12;\n" +
	"\tDeleteTag\x12\x16.core.DeleteTagRequest\x1a\x16.google.protobuf.Empty\x12:\n" +
	"\bListTags\x12\x16.google.protobuf.Empty\x1a\x16.core.ListTagsResponse\x12?\n" +
	"\x0fGetNextQuestion\x12\x1c.core.GetNextQuestionRequest\x1a\x0e.core.Question\x12C\n" +
	"\x0fGetUserProgress\x12\x1c.core.GetUserProgressRequest\x1a\x12.core.UserProgress\x12=\n" +
	"\fRecordAnswer\x12\x19.core.RecordAnswerRequest\x1a\x12.core.UserProgressB0Z.github.com/swarley72/interview-dojo/proto/coreb\x06proto3"

var (
	file_proto_core_core_proto_rawDescOnce sync.Once
	file_proto_core_core_proto_rawDescData []byte
)

func file_proto_core_core_proto_rawDescGZIP() []byte {
	file_proto_core_core_proto_rawDescOnce.Do(func() {
		file_proto_core_core_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_core_core_proto_rawDesc), len(file_proto_core_core_proto_rawDesc)))
	})
	return file_proto_core_core_proto_rawDescData
}

var file_proto_core_core_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_core_core_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_core_core_proto_goTypes = []any{
	(Difficulty)(0),                // 0: core.Difficulty
	(QuestionType)(0),              // 1: core.QuestionType
	(AnswerQuality)(0),             // 2: core.AnswerQuality
	(*Tag)(nil),                    // 3: core.Tag
	(*Question)(nil),               // 4: core.Question
	(*UserProgress)(nil),           // 5: core.UserProgress
	(*GetQuestionRequest)(nil),     // 6: core.GetQuestionRequest
	(*ListQuestionsRequest)(nil),   // 7: core.ListQuestionsRequest
	(*ListQuestionsResponse)(nil),  // 8: core.ListQuestionsResponse
	(*CreateQuestionRequest)(nil),  // 9: core.CreateQuestionRequest
	(*DeleteQuestionRequest)(nil),  // 10: core.DeleteQuestionRequest
	(*UpdateQuestionRequest)(nil),  // 11: core.UpdateQuestionRequest
	(*CreateTagRequest)(nil),       // 12: core.CreateTagRequest
	(*DeleteTagRequest)(nil),       // 13: core.DeleteTagRequest
	(*ListTagsResponse)(nil),       // 14: core.ListTagsResponse
	(*GetNextQuestionRequest)(nil), // 15: core.GetNextQuestionRequest
	(*GetUserProgressRequest)(nil), // 16: core.GetUserProgressRequest
	(*RecordAnswerRequest)(nil),    // 17: core.RecordAnswerRequest
	(*timestamppb.Timestamp)(nil),  // 18: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),          // 19: google.protobuf.Empty
}
var file_proto_core_core_proto_depIdxs = []int32{
	0,  // 0: core.Question.difficulty:type_name -> core.Difficulty
	1,  // 1: core.Question.type:type_name -> core.QuestionType
	18, // 2: core.Question.created_at:type_name -> google.protobuf.Timestamp
	18, // 3: core.Question.updated_at:type_name -> google.protobuf.Timestamp
	18, // 4: core.UserProgress.last_reviewed_at:type_name -> google.protobuf.Timestamp
	18, // 5: core.UserProgress.next_review_at:type_name -> google.protobuf.Timestamp
	1,  // 6: core.ListQuestionsRequest.type:type_name -> core.QuestionType
	0,  // 7: core.ListQuestionsRequest.difficulty:type_name -> core.Difficulty
	4,  // 8: core.ListQuestionsResponse.questions:type_name -> core.Question
	0,  // 9: core.CreateQuestionRequest.difficulty:type_name -> core.Difficulty
	1,  // 10: core.CreateQuestionRequest.type:type_name -> core.QuestionType
	1,  // 11: core.UpdateQuestionRequest.type:type_name -> core.QuestionType
	0,  // 12: core.UpdateQuestionRequest.difficulty:type_name -> core.Difficulty
	3,  // 13: core.ListTagsResponse.tags:type_name -> core.Tag
	1,  // 14: core.GetNextQuestionRequest.type:type_name -> core.QuestionType
	2,  // 15: core.RecordAnswerRequest.answer_quality:type_name -> core.AnswerQuality
	6,  // 16: core.CoreService.GetQuestion:input_type -> core.GetQuestionRequest
	7,  // 17: core.CoreService.ListQuestions:input_type -> core.ListQuestionsRequest
	9,  // 18: core.CoreService.CreateQuestion:input_type -> core.CreateQuestionRequest
	10, // 19: core.CoreService.DeleteQuestion:input_type -> core.DeleteQuestionRequest
	11, // 20: core.CoreService.UpdateQuestion:input_type -> core.UpdateQuestionRequest
	12, // 21: core.CoreService.CreateTag:input_type -> core.CreateTagRequest
	13, // 22: core.CoreService.DeleteTag:input_type -> core.DeleteTagRequest
	19, // 23: core.CoreService.ListTags:input_type -> google.protobuf.Empty
	15, // 24: core.CoreService.GetNextQuestion:input_type -> core.GetNextQuestionRequest
	16, // 25: core.CoreService.GetUserProgress:input_type -> core.GetUserProgressRequest
	17, // 26: core.CoreService.RecordAnswer:input_type -> core.RecordAnswerRequest
	4,  // 27: core.CoreService.GetQuestion:output_type -> core.Question
	8,  // 28: core.CoreService.ListQuestions:output_type -> core.ListQuestionsResponse
	4,  // 29: core.CoreService.CreateQuestion:output_type -> core.Question
	19, // 30: core.CoreService.DeleteQuestion:output_type -> google.protobuf.Empty
	4,  // 31: core.CoreService.UpdateQuestion:output_type -> core.Question
	3,  // 32: core.CoreService.CreateTag:output_type -> core.Tag
	19, // 33: core.CoreService.DeleteTag:output_type -> google.protobuf.Empty
	14, // 34: core.CoreService.ListTags:output_type -> core.ListTagsResponse
	4,  // 35: core.CoreService.GetNextQuestion:output_type -> core.Question
	5,  // 36: core.CoreService.GetUserProgress:output_type -> core.UserProgress
	5,  // 37: core.CoreService.RecordAnswer:output_type -> core.UserProgress
	27, // [27:38] is the sub-list for method output_type
	16, // [16:27] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_proto_core_core_proto_init() }
func file_proto_core_core_proto_init() {
	if File_proto_core_core_proto != nil {
		return
	}
	file_proto_core_core_proto_msgTypes[1].OneofWrappers = []any{}
	file_proto_core_core_proto_msgTypes[4].OneofWrappers = []any{}
	file_proto_core_core_proto_msgTypes[6].OneofWrappers = []any{}
	file_proto_core_core_proto_msgTypes[8].OneofWrappers = []any{}
	file_proto_core_core_proto_msgTypes[12].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_core_core_proto_rawDesc), len(file_proto_core_core_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_core_core_proto_goTypes,
		DependencyIndexes: file_proto_core_core_proto_depIdxs,
		EnumInfos:         file_proto_core_core_proto_enumTypes,
		MessageInfos:      file_proto_core_core_proto_msgTypes,
	}.Build()
	File_proto_core_core_proto = out.File
	file_proto_core_core_proto_goTypes = nil
	file_proto_core_core_proto_depIdxs = nil
}
